<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{{ $document->title }}</title>
    <style>
        @page { margin: 18mm 12mm 14mm; }
        * { box-sizing: border-box; }
        body { font-family: DejaVu Sans, sans-serif; color: #18181b; font-size: 9px; margin: 0; }
        .association-page { page-break-before: always; }
        .association-page:first-child { page-break-before: auto; }
        .brand { color: #4f46e5; font-size: 10px; font-weight: bold; letter-spacing: .08em; text-transform: uppercase; }
        h1 { font-size: 19px; margin: 5px 0 3px; }
        h2 { font-size: 13px; margin: 12px 0 7px; color: #3730a3; }
        .meta { width: 100%; margin: 7px 0 10px; border-collapse: collapse; }
        .meta td { padding: 2px 12px 2px 0; vertical-align: top; }
        .meta-label { color: #71717a; font-size: 8px; text-transform: uppercase; font-weight: bold; }
        .meta-value { font-size: 9px; font-weight: bold; }
        table.attendance { width: 100%; border-collapse: collapse; table-layout: fixed; }
        table.attendance thead { display: table-header-group; }
        table.attendance tr { page-break-inside: avoid; }
        table.attendance th { background: #eef2ff; color: #312e81; border: 1px solid #a5b4fc; padding: 6px 5px; text-align: left; font-size: 8px; text-transform: uppercase; }
        table.attendance td { border: 1px solid #cbd5e1; padding: 6px 5px; height: 34px; vertical-align: middle; overflow: hidden; }
        .col-no { width: 4%; text-align: center; }
        .col-last { width: 14%; }
        .col-first { width: 14%; }
        .col-org { width: 18%; }
        .col-email { width: 19%; }
        .col-phone { width: 12%; }
        .col-sign { width: 19%; }
        .muted { color: #71717a; }
        .summary { margin-top: 7px; color: #52525b; font-size: 8px; }
        .footer { position: fixed; left: 0; right: 0; bottom: -8mm; color: #71717a; font-size: 8px; text-align: right; }
    </style>
</head>
<body>
<div class="footer">Generated by MobilityCloud</div>
@forelse($groups as $organisation => $participants)
    <section class="association-page">
        <div class="brand">MobilityCloud - Attendance record</div>
        <h1>{{ $project->name }}</h1>
        <table class="meta">
            <tr>
                <td><div class="meta-label">Activity</div><div class="meta-value">{{ $document->activity_title }}</div></td>
                <td><div class="meta-label">Date</div><div class="meta-value">{{ $document->activity_date?->format('d M Y') }}</div></td>
                <td><div class="meta-label">Location</div><div class="meta-value">{{ $document->location ?: '-' }}</div></td>
                <td><div class="meta-label">Grant reference</div><div class="meta-value">{{ $project->grant_ref ?: '-' }}</div></td>
            </tr>
        </table>

        <h2>{{ $organisation }}</h2>

        <table class="attendance">
            <thead>
            <tr>
                <th class="col-no">No.</th>
                <th class="col-last">Last name</th>
                <th class="col-first">First name</th>
                <th class="col-org">Organisation</th>
                <th class="col-email">Email</th>
                <th class="col-phone">Phone</th>
                <th class="col-sign">Signature</th>
            </tr>
            </thead>
            <tbody>
            @foreach($participants as $participant)
                <tr>
                    <td class="col-no">{{ $loop->iteration }}</td>
                    <td>{{ $participant->last_name }}</td>
                    <td>{{ $participant->first_name }}</td>
                    <td>{{ $participant->partner_organisation ?: 'Unassigned' }}</td>
                    <td>{{ $participant->email ?: '-' }}</td>
                    <td>{{ $participant->phone ?: '-' }}</td>
                    <td></td>
                </tr>
            @endforeach
            </tbody>
        </table>
        <div class="summary">{{ $participants->count() }} participant{{ $participants->count() === 1 ? '' : 's' }}</div>
    </section>
@empty
    <section>
        <div class="brand">MobilityCloud - Attendance record</div>
        <h1>{{ $project->name }}</h1>
        <p class="muted">No participants are registered for this project.</p>
    </section>
@endforelse

</body>
</html>
