<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Service Acceptance Certificate</title>
    <style>
        @page { margin: 20mm 18mm 18mm; }
        * { box-sizing:border-box; }
        body { font-family:DejaVu Sans, sans-serif; color:#18181b; font-size:10px; line-height:1.45; margin:0; }
        .header { border-bottom:1px solid #c7d2fe; padding-bottom:8px; margin-bottom:20px; }
        .brand { color:#4f46e5; font-size:9px; font-weight:bold; text-transform:uppercase; letter-spacing:.08em; }
        .project { color:#71717a; font-size:8.5px; margin-top:2px; }
        h1 { font-size:19px; text-align:center; margin:18px 0 4px; }
        .subtitle { text-align:center; color:#52525b; margin-bottom:24px; }
        h2 { color:#312e81; font-size:11px; margin:16px 0 6px; }
        p { margin:0 0 8px; text-align:justify; }
        .box { border:1px solid #cbd5e1; background:#f8fafc; padding:12px 14px; margin:8px 0 14px; }
        .status { display:inline-block; padding:5px 10px; border-radius:12px; background:#dcfce7; color:#166534; font-weight:bold; }
        .facts { width:100%; border-collapse:collapse; margin:10px 0 16px; }
        .facts th, .facts td { border:1px solid #cbd5e1; padding:7px 9px; text-align:left; }
        .facts th { width:27%; background:#eef2ff; color:#312e81; }
        .signatures { width:100%; border-collapse:collapse; margin-top:42px; page-break-inside:avoid; }
        .signatures td { width:50%; vertical-align:top; padding:9px 12px 55px; border-top:1px solid #a1a1aa; }
        .footer { position:fixed; bottom:-11mm; left:0; right:0; text-align:center; color:#71717a; font-size:7.5px; }
    </style>
</head>
<body>
<div class="footer">Generated by MobilityCloud - review before signature</div>
<div class="header">
    <div class="brand">{{ $data['beneficiary_name'] ?: $project->workspace->name }}</div>
    <div class="project">{{ $project->name }}@if($project->grant_ref) · {{ $project->grant_ref }}@endif</div>
</div>

<h1>SERVICE ACCEPTANCE CERTIFICATE</h1>
<div class="subtitle">Related agreement no. {{ $data['convention_number'] }}</div>

<p>This certificate is concluded on <strong>{{ \Carbon\Carbon::parse($data['acceptance_date'])->format('d F Y') }}</strong>@if($data['acceptance_place']) in <strong>{{ $data['acceptance_place'] }}</strong>@endif between:</p>

<table class="facts">
    <tr><th>Beneficiary</th><td>{{ $data['beneficiary_name'] ?: $project->workspace->name }}</td></tr>
    <tr><th>{{ ($data['agreement_type'] ?? 'service_agreement') === 'copyright_assignment' ? 'Author' : 'Service provider' }}</th><td>{{ $data['provider_name'] }}</td></tr>
    <tr><th>Agreement</th><td>No. {{ $data['convention_number'] }}, dated {{ \Carbon\Carbon::parse($data['contract_date'])->format('d F Y') }}</td></tr>
    <tr><th>Agreed gross fee</th><td>{{ number_format((float) $data['gross_amount'], 2) }} {{ $data['currency'] }}</td></tr>
</table>

<h2>DELIVERED AND REVIEWED</h2>
<div class="box">{!! nl2br(e($data['acceptance_deliverables'])) !!}</div>

<h2>ACCEPTANCE</h2>
<p>The Beneficiary confirms that the services, deliverables or work described above have been reviewed against the related agreement.</p>
<p><span class="status">{{ strtoupper($statusLabel) }}</span></p>

@if(!empty($data['acceptance_notes']))
    <h2>OBSERVATIONS / RESERVATIONS</h2>
    <div class="box">{!! nl2br(e($data['acceptance_notes'])) !!}</div>
@else
    <p>No observations or reservations were recorded at the date of signature.</p>
@endif

<p>By signing this certificate, the parties confirm the status stated above. Where the services or work are accepted without reservations, the agreed payment may be processed under the conditions of the related agreement.</p>

<table class="signatures">
    <tr>
        <td><strong>BENEFICIARY</strong><br>{{ $data['beneficiary_name'] ?: $project->workspace->name }}<br><br>Name: {{ $data['beneficiary_representative'] ?: '________________' }}<br>Signature: ____________________</td>
        <td><strong>{{ ($data['agreement_type'] ?? 'service_agreement') === 'copyright_assignment' ? 'AUTHOR' : 'SERVICE PROVIDER' }}</strong><br>{{ $data['provider_name'] }}<br><br>Signature: ____________________</td>
    </tr>
</table>
</body>
</html>
